# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуmailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - iv-maxim@ya.ru
    on_success: never # default: change
    on_failure: always # default: always

services:
- postgresql

before_script:
- psql -c 'create database base;' -U postgres
- psql -c 'create database todolist;' -U postgres
- psql -c 'create database carprice;' -U postgres
- sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"
